# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist = flake8,black,doctests,py{36,310},cov
deps = -rrequirements.txt
skip_missing_interpreters = true

[gh]
# splitting the subtests among each environment for speed reasons
python =
    3.6  = py36
    3.10 = py310

[travis]
# splitting the subtests among each environment for speed reasons
python =
    3.6: flake8,black,py36
    3.10: py310,cov,doctests

[testenv:black]
deps =
    black
commands = black --check --diff --fast .

[testenv:flake8]
deps =
    flake8
    flake8-black
    flake8-docstrings
    flake8-quotes
    pep8-naming
commands = flake8

[flake8]
# use 160 because some comments are too long
max-line-length = 160
max-complexity = 10
# isort and documentation flags, minor importance
ignore = I002,D100,D103,D104,D203,D204,D211,E402,Q000,W503
exclude = .ropeproject/,.tox/,venv/,version.py

[testenv:doctests]
# only run doctest on main modules to prevent parsing all files including
# setup.py which can fail
commands =
    py.test --doctest-modules openqabot/
deps = -rrequirements.txt
    pytest
    pytest-doc

[testenv:cov]
# necessary to make cov find the .coverage file
# see http://stackoverflow.com/a/34706770/5031322
usedevelop = true
# Ignore exit code of first command as this will always fail
commands =
    - py.test --cov=openqabot --doctest-modules openqabot/
    py.test --cov=openqabot --cov-append
deps = -rrequirements.txt
    pytest
    pytest-cov
    pytest-mock

[testenv]
commands =
    py.test
deps = -rrequirements.txt
    pytest
    pytest-mock

